# <center> Workshop - Intro to MDAnalysis</center>


In [3]:
import warnings
warnings.filterwarnings("ignore") 

# Distance calculations in MDAnalysis

Atom coordinates are in the 
`.positions` attribute of an `AtomGroup`

The positions are returned as a NumPy array, which we can then readily manipulate.

Some built-in functions based on position data:

- `center_of_mass()`

- `center_of_geometry()`



In [4]:
# First we import MDAnalysis
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD

u = mda.Universe(PSF, DCD)
pos = u.atoms.positions
pos

array([[ 11.736044 ,   8.500797 , -10.445281 ],
       [ 12.365119 ,   7.839936 , -10.834842 ],
       [ 12.0919485,   9.441535 , -10.724611 ],
       ...,
       [  6.512604 ,  18.447018 ,  -7.134053 ],
       [  6.300186 ,  19.363485 ,  -7.935916 ],
       [  5.5854015,  17.589624 ,  -6.9656615]], dtype=float32)

# The `lib.distances` module

Particle positions are given as numpy arrays, so most work can be done using numpy (and numpy derived) libraries.

MDAnalysis  `lib.distances` module comes handy when

- we have periodic boundary conditions 

- domain specific algorithms can be used


# `distance_array`

To calculate all pairwise distances between two arrays of coordinates.

In [26]:
from MDAnalysis.lib import distances


ag1 = u.atoms[:10]
ag2 = u.atoms[:-10]

reference = ag1.positions
configuration = ag2.positions

da = distances.distance_array(reference, 
                         configuration,
                         box=u.dimensions)
print(da.shape)
print(da)

(10, 3331)
[[0.         0.9920841  1.04387783 ... 9.09150004 7.8105948  9.09971745]
 [0.9920841  0.         1.62846336 ... 9.9430324  8.70396582 9.93966063]
 [1.04387783 1.62846336 0.         ... 9.0507164  7.82633649 9.24420786]
 ...
 [2.67831878 3.60064083 3.02210083 ... 6.98287171 5.50558527 6.7658636 ]
 [2.48649473 3.41418661 2.15870939 ... 6.94746882 5.71699641 7.21281159]
 [3.81500409 4.63829735 3.95581602 ... 5.31906104 4.1259778  5.36780012]]


# `self_distance_array`

For calculating distances between all combinations of coordinates.

Takes a single array of coordinates and calculates all pairwise distances ( ½ n(n-1) results).


In [9]:
distances.self_distance_array(reference, box=None, result=None)

array([0.9920841 , 1.04387783, 1.05986122, 1.4677231 , 1.99856019,
       2.36117508, 2.67831878, 2.48649473, 3.81500409, 1.62846336,
       1.60838714, 2.0556173 , 2.29211662, 3.26665051, 3.60064083,
       3.41418661, 4.63829735, 1.71124615, 2.07688445, 2.30015734,
       2.52954317, 3.02210083, 2.15870939, 3.95581602, 2.15028073,
       2.94351899, 2.68913032, 2.51650006, 2.87640887, 4.18963886,
       1.0655627 , 1.54715331, 2.20757331, 2.20623844, 2.66493636,
       2.18253486, 3.12900115, 2.55697562, 2.97064033, 1.20158828,
       1.15342801, 1.53357976, 1.92567233, 2.17396078, 2.1796127 ])

# `calc_bonds`

For calculating a series of distances between points.

Takes 2 arrays of coordinates **of equal length**, and returns the distances between coordinate pairs in each row.


In [20]:
coords1 = u.atoms[:10].positions
coords2 = u.atoms[10:20].positions
dist = distances.calc_bonds(coords1, 
                     coords2, 
                     box=None)
print(dist)

[4.18088681 4.85935014 5.03940839 5.66651264 4.12341026 5.53698907
 3.78848949 2.69663056 4.00235462 3.5374006 ]


# `calc_angles` & `calc_dihedrals`

Same as `calc_bonds`

Calculate either the angle or dihedral angle between 3 or 4 arrays of coordinates.

Takes 3 or 4 arrays of identical length coordinates.


In [35]:
import numpy as np
coords1 = u.atoms[:10].positions
coords2 = u.atoms[10:20].positions
coords3 = u.atoms[20:30].positions

angles = distances.calc_angles(
coords1, coords2, coords3,
box=None, result=None)

print(np.rad2deg(angles))


[ 60.1705515   70.44413816  61.74292062  48.97993666  31.49563244
  31.70597945  15.62738421 162.62889398 125.52167306 148.32427929]


# Minimum image convention

To account for periodic boundary conditions in distance calculations,
pass the box information as `box=ag.dimensions` to any distance function.


# `capped_distance` and `self_capped_distance`

Only find distances up to a limit. It returns:
- an array of indices
- an array of distances


In [44]:
ix, dist = distances.capped_distance(reference, 
                          configuration, 
                          min_cutoff = 3,
                          max_cutoff=4,
                          box=u.dimensions)
ix[:3], dist[:3]

(array([[   0, 1214],
        [   0, 1209],
        [   0,  390]]),
 array([3.07942888, 3.81926148, 3.99841942]))

2022-07-26 11:19:45 2022-07-26 11:19:46 ## A summary of Lecture 1

Most simulation analysis will involve extracting position data from certain atoms.

- A `Universe` contains all information about a simulation system

- An `AtomGroup` contains information about a group of atoms

- We can use `Universe.select_atoms()` to create an `AtomGroup` containing specific atoms from a `Universe`

- Positions of atoms in an AtomGroup are accessed through `AtomGroup.positions`

# A summary of Lecture 2

Calculating pairwise distances:
- calc_bonds
- distance_array
- self_distance_array

Faster, sparse pairwise distances:
- capped_distance
- self_capped_distance

Calculating angles:
- calc_angles
- calc_dihedrals


## Now - on to the second tutorial!

Find the tutorial notebook `Tutorial2_Distances_Trajectories` under: 

https://github.com/MDAnalysis/MDAnalysisWorkshop-Intro1Day/blob/may24-ws/notebooks/Tutorial2_Distances_Trajectories.ipynb

**Remember:**
- Go at your own pace!
- Ask questions!
- Take breaks!